### PR TITLE
Requested Bug Fixes & Enhancements

### PR DESCRIPTION
**Pull request by maxboynton**
## Description

Fixes and enhancements as requested by users via GitHub.

## Motivation and Context

Fixes for the following issues:

- #38
- #46
- #48
- #49
	- Currently an issue with specifying the "All" collection that is built in within Prisma.
- #51
- #59
- #63
- #64
- #65
	- This issue will only occur if policy categories that are not relevant to the selected alert type, of which only webhooks are currently supported. For example, the `admission` policy is not relevant to webhook alert profiles, but can be specified in the TF resource without affecting anything. It will, however, show up as a modification in the TF plan even though applying it won't actually change anything. The provider documentation will be updated to reflect the necessary fields for each alert type in the near future.
- #66
	- This is an initial implementation that will be enhanced in future updates
- #68 
- #72 
## How Has This Been Tested?

Testing was done against internal PC tenant.

## Types of changes

- Bug fix (non-breaking change which fixes an issue)

## Checklist

- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes if appropriate.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by hi-artem — COMMENTED** [review]
Hi @maxboynton. I did the initial testing of these PR against PCC console version 30.01.153, and the following Terraform sample template:

```tf
resource "prismacloudcompute_container_runtime_policy" "ruleset" {
  learning_disabled = false
  rule {
    name                              = "string"
    collections                       = ["All"]
    advanced_protection_effect        = "disable"
    cloud_metadata_enforcement_effect = "disable"
    # previous_name                     = "string" # Required if Renaming the Rule
    skip_exec_sessions                = false    # true | false
    wildfire_analysis                 = "alert"  # "block" | "prevent" | "alert" | "disable"

    dns {
      default_effect = "alert" # "block" | "prevent" | "alert" | "disable"
      disabled       = true
      domain_list {
        allowed = ["0.0.0.0"]
        denied  = ["1.1.1.1"]
        effect  = "disable"
      }
    }
    filesystem {
      allowed_list          = ["string"]
      backdoor_files_effect = "disable" # "block" | "prevent" | "alert" | "disable"
      default_effect        = "alert"   # "block" | "prevent" | "alert" | "disable"
      denied_list {
        effect = "disable" # "block" | "prevent" | "alert" | "disable"
        paths  = ["string"]
      }
      disabled                      = true
      encrypted_binaries_effect     = "disable"
      new_files_effect              = "disable"
      suspicious_elf_headers_effect = "disable"
    }
    kubernetes_enforcement_effect = "disable"
    network {
      allowed_ips       = ["0.0.0.0"]
      default_effect    = "alert"
      denied_ips        = ["1.1.1.1"]
      denied_ips_effect = "disable"
      disabled          = true
      listening_ports {
        allowed {
          deny  = true
          end   = 333
          start = 222
        }
        denied {
          deny  = true
          end   = 5000
          start = 4000
        }
        denied {
          deny  = true
          end   = 222
          start = 111
        }
        effect = "disable" # "block" | "prevent" | "alert" | "disable"
      }
      modified_proc_effect = "disable" # "block" | "prevent" | "alert" | "disable"
      outbound_ports {
        allowed {
          deny  = true
          end   = 300
          start = 200
        }
        denied {
          deny  = true
          end   = 6000
          start = 5000
        }
        denied {
          deny  = true
          end   = 222
          start = 111
        }
        effect = "disable" # "block" | "prevent" | "alert" | "disable"
      }
      port_scan_effect   = "disable" # "block" | "prevent" | "alert" | "disable"
      raw_sockets_effect = "disable" # "block" | "prevent" | "alert" | "disable"
    }
    processes {
      modified_process_effect = "disable" # "block" | "prevent" | "alert" | "disable"
      crypto_miners_effect    = "disable" # "block" | "prevent" | "alert" | "disable"
      lateral_movement_effect = "disable" # "block" | "prevent" | "alert" | "disable"
      reverse_shell_effect    = "disable" # "block" | "prevent" | "alert" | "disable"
      suid_binaries_effect    = "disable" # "block" | "prevent" | "alert" | "disable"
      default_effect          = "alert"   # "block" | "prevent" | "alert" | "disable"
      check_parent_child      = false
      allowed_list            = []
      disabled                = false
      denied_list {
        effect = "disable" # "block" | "prevent" | "alert" | "disable"
        paths  = ["test"]
      }
    }
  }
}
```

The provisioned resource looks expected in the tenant. I will do some additional testing with our internal code-base, as well as reviewing the code in the upcoming day, but thought you might want to hear this update.

**Comment by adrianfuro** [comment]
I built this PR as well locally and apparently fixes the 400 error when trying to deploy Container Runtime Rule resource. Could you point out to where was the changes that you've done that fixed that issue, if you were aware with it.

**Comment by hi-artem** [comment]
> I built this PR as well locally and apparently fixes the 400 error when trying to deploy Container Runtime Rule resource. Could you point out to where was the changes that you've done that fixed that issue, if you were aware with it.

How does your `prismacloudcompute_container_runtime_policy` resource looks like?

**Comment by hi-artem** [comment]
@maxboynton I did some further testing on this change, and it looks good on my end so far. I updated our internal module, and was able to recreate all the policies migrating from PCC Console v22.xxx to v30.xxx without any issues.

**Comment by hi-artem** [comment]
For reference, this fixes #68

**Review by hi-artem — APPROVED** [review]
lgtm

**Comment by maxboynton** [comment]
> @maxboynton I did some further testing on this change, and it looks good on my end so far. I updated our internal module, and was able to recreate all the policies migrating from PCC Console v22.xxx to v30.xxx without any issues.

Glad to hear it! Thank you for testing! Let me know if any issues come up.

**Comment by PANW-aharrell** [comment]
Version 0.8.0

**Pull request merged**
